### ISSUE TITLE
[BUG] OrderedDict object has no attribute 'version_cmp'

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/salt-formula#459]
### Formula commit hash / release tag

Master

### Versions reports (master & minion)
```
(base) OCIR-LM20540:salt-formula nmcloughlin$ salt --versions-report
/usr/local/Cellar/salt/3000/libexec/lib/python3.7/site-packages/salt/ext/tornado/httputil.py:107: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  class HTTPHeaders(collections.MutableMapping):
Salt Version:
           Salt: 3000
 
Dependency Versions:
           cffi: 1.13.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.3
        libgit2: 0.28.4
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.28.2
         Python: 3.7.7 (default, Mar 10 2020, 15:43:03)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.1.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 18.7.0
         system: Darwin
        version: 10.14.6 x86_64
```

### Pillar / config used
---

### Describe the bug
This is the bug output

```
    Rendering SLS 'base:salt.formulas' failed: Jinja variable 
      'salt.utils.odict.OrderedDict object' has no attribute 'version_cmp'
```

This is the SLS part..
```
formulas.sls:    - parallel: {{ salt.pkg.version_cmp(grains['saltversion'], '2017.7.0') >= 0 }}
```

### Steps to reproduce the bug
Running on macOS, python 3.7.3

### Expected behaviour
No bug

**Comment by myii** [comment]
So this is the `pkg.version_cmp` module, which is available for some of the platforms but not others, some examples being:

* Available:
  - https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.aptpkg.html#salt.modules.aptpkg.version_cmp
  - https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.yumpkg.html#salt.modules.yumpkg.version_cmp
* Unavailable:
  - https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.mac_brew_pkg.html
  - https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.win_pkg.html

This was introduced by #445.

**Comment by noelmcloughlin** [comment]
By the way, is this correct in salt-versions?  I never saw `3000` version before.
```
Salt Version:
           Salt: 3000
```

**Comment by myii** [comment]
> By the way, is this correct in salt-versions? I never saw `3000` version before.

Where have you been?!  You missed all of the fun.  Yep, `Neon` was release as version `3000`.  `Sodium` will be `3001` and so on.  You can read more about it here:

* https://github.com/saltstack/salt-enhancement-proposals/blob/master/accepted/0014-dev-overhaul.md
