### ISSUE TITLE
[CentOS 6] `mapping` test not supported, master config cannot be generated

### ISSUE THREAD

**Issue by blast-hardcheese** [saltstack-formulas/salt-formula#193]
Unfortunately, since CentOS 6 only ships with Jinja2 2.2.1, the `mapping` test is not supported. Looking through the documentation, I don't see anything else equivalent to it (both `iterable` and `sequence` test true for dicts and lists), so I'm not sure how to maintian functionality without that test.

Tapping @sjd-Risca, just in case they have some idea

**Comment by blast-hardcheese** [comment]
Until this is resolved, the last good version that works on CentOS 6 is a33937d9e85b577ac1e944a25ef9fe6fae770a47

**Comment by gravyboat** [comment]
Hmm, could we create a flag to include a different file if the os grain is centos 6? I can't remember if it would still get parsed in that situation.

**Comment by 0xf10e** [comment]
Seriously, no one will like this hack, but at least it renders:
```
{% if 'ext_pillar' in cfg_master %}
{#- workaround for missing mapping test in CentOS 6, part A #}
{%- set is_mapping = {} %}
ext_pillar:
{%- for pillar in cfg_master['ext_pillar'] -%}
  {%- for key in pillar -%}
    {%- if pillar[key] is string %}
  - {{ key }}: {{ pillar[key] }}
    {#- workaround for missing mapping test in CentOS 6, part B #}
    {%- do is_mapping.update({key: type(pillar[key]) == type({})}) %}
    {%- elif pillar[key] is iterable and not is_mapping[key] %}
  - {{ key }}:
      {%- for parameter in pillar[key] %}
    - {{ parameter }}
      {%- endfor -%}
    {#- workaround for missing mapping test in CentOS 6, part C #}
    {%- elif is_mapping[key] and pillar[key] is not string %}
```

**Comment by 0xf10e** [comment]
(I got this hack in a local git-clone of the formula if anyone is interested)

**Comment by mchugh19** [comment]
The mapping configs also affect minion runs.

```
SaltRenderError: Jinja syntax error: no test named 'mapping'; line 671

              ---
              [...]
              ext_pillar:
              {%- for pillar in cfg_minion['ext_pillar'] -%}
                {%- for key in pillar -%}
                  {%- if pillar[key] is string %}
                - {{ key }}: {{ pillar[key] }}
                  {%- elif pillar[key] is iterable and pillar[key] is not mapping %}    <======================
```

**Comment by mchugh19** [comment]
@0xf10e Would you be interested in submitting a PR? The missing jinja mapping logic now breaks RHEL6 minions and masters.

**Comment by 0xf10e** [comment]
@mchugh19 Oh, this is still open? Let me see if my diff still applies...

**Comment by 0xf10e** [comment]
:warning: #298 is not tested yet! :warning:

**Comment by 0xf10e** [comment]
As mentions in #298: Only tested basic functionality on CentOS 6.
Not tried CentOS 7, Debian, Ubuntu, *BSD... yet (and won't today).

**Comment by tedski** [comment]
#298 breaks Debian latest (isolated to e86e6fc via `git bisect`):

```
    Data failed to compile:
----------
    Rendering SLS 'base:salt.gitfs.pygit2' failed: Jinja variable 'dict object' has no attribute 'build_parent_dir'
```

**Comment by aboe76** [comment]
If I look in the changelog file of jinja2 version 2.6 has mapping:
http://jinja.pocoo.org/docs/2.10/changelog/#version-2-6

and the salt repo for centos 6 py27, already ships with jinja2 2.8.1 

I don't think this is necessary any more and we can opt for a cleaner map.jinja
maybe something like the apache-formula:
 - map.jinja
 - defaults.yaml
 - osfamilymap.yaml
 - oscodenamemap.yaml
 - osfingermap.yaml

which will in turn keep everything nice and separated. which is easier to maintain and contribute.

**Comment by jeff350** [comment]
Closing issue as this was addressed in #395 and CentOS 6 went EOL in 2020
